import { localDateOf, localMinutesOf, weekdayOf } from "../time";

/**
 * Appointment times in words, the way people say them (Build Prompt §6.3):
 *   en        "Tuesday, 14 October, 5:30 pm"
 *   hi        "मंगलवार, 14 अक्टूबर, शाम साढ़े 5 बजे"
 *   hinglish  "Mangalvaar, 14 October, shaam saadhe 5 baje"
 * Generated by code, never by the LLM, so the day and date cannot be wrong.
 */
export type Lang = "en" | "hi" | "hinglish";

const WEEKDAYS = {
  en: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  hi: ["रविवार", "सोमवार", "मंगलवार", "बुधवार", "गुरुवार", "शुक्रवार", "शनिवार"],
  hinglish: ["Ravivaar", "Somvaar", "Mangalvaar", "Budhvaar", "Guruvaar", "Shukravaar", "Shanivaar"],
};
const MONTHS = {
  en: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  hi: [
    "जनवरी",
    "फ़रवरी",
    "मार्च",
    "अप्रैल",
    "मई",
    "जून",
    "जुलाई",
    "अगस्त",
    "सितंबर",
    "अक्टूबर",
    "नवंबर",
    "दिसंबर",
  ],
};

function partOfDay(minutes: number, lang: "hi" | "hinglish"): string {
  const words = lang === "hi" ? ["सुबह", "दोपहर", "शाम", "रात"] : ["subah", "dopahar", "shaam", "raat"];
  if (minutes >= 5 * 60 && minutes < 12 * 60) return words[0]!;
  if (minutes >= 12 * 60 && minutes < 16 * 60) return words[1]!;
  if (minutes >= 16 * 60 && minutes < 19 * 60 + 30) return words[2]!;
  return words[3]!;
}

/** "5 baje", "sawa 5 baje", "saadhe 5 baje", "paune 6 baje", "dedh baje", "dhaai baje", else "5:10 baje". */
function hindiClock(minutes: number, lang: "hi" | "hinglish"): string {
  const h24 = Math.floor(minutes / 60);
  const m = minutes % 60;
  const h = ((h24 + 11) % 12) + 1;
  const next = (h % 12) + 1;
  const w =
    lang === "hi"
      ? { baje: "बजे", sawa: "सवा", saadhe: "साढ़े", paune: "पौने", dedh: "डेढ़", dhaai: "ढाई" }
      : { baje: "baje", sawa: "sawa", saadhe: "saadhe", paune: "paune", dedh: "dedh", dhaai: "dhaai" };
  if (m === 0) return `${h} ${w.baje}`;
  if (m === 15) return `${w.sawa} ${h} ${w.baje}`;
  if (m === 30)
    return h === 1 ? `${w.dedh} ${w.baje}` : h === 2 ? `${w.dhaai} ${w.baje}` : `${w.saadhe} ${h} ${w.baje}`;
  if (m === 45) return `${w.paune} ${next} ${w.baje}`;
  return `${h}:${String(m).padStart(2, "0")} ${w.baje}`;
}

export function clockInWords(instant: Date, timezone: string, lang: Lang): string {
  const minutes = localMinutesOf(instant, timezone);
  if (lang === "en") {
    const h = ((Math.floor(minutes / 60) + 11) % 12) + 1;
    return `${h}:${String(minutes % 60).padStart(2, "0")} ${minutes < 12 * 60 ? "am" : "pm"}`;
  }
  return `${partOfDay(minutes, lang)} ${hindiClock(minutes, lang)}`;
}

export function dayInWords(instant: Date, timezone: string, lang: Lang): string {
  const date = localDateOf(instant, timezone);
  const weekday = WEEKDAYS[lang][weekdayOf(date)]!;
  const day = Number(date.slice(8, 10));
  const month = (lang === "hi" ? MONTHS.hi : MONTHS.en)[Number(date.slice(5, 7)) - 1]!;
  return `${weekday}, ${day} ${month}`;
}

export function whenInWords(instant: Date, timezone: string, lang: Lang): string {
  return `${dayInWords(instant, timezone, lang)}, ${clockInWords(instant, timezone, lang)}`;
}

/** Short label for a WhatsApp button (max 20 characters), e.g. "Tue 14 Oct 5:30pm". */
export function buttonLabel(instant: Date, timezone: string, lang: Lang): string {
  const date = localDateOf(instant, timezone);
  const minutes = localMinutesOf(instant, timezone);
  const day = Number(date.slice(8, 10));
  const monthIdx = Number(date.slice(5, 7)) - 1;
  const h = ((Math.floor(minutes / 60) + 11) % 12) + 1;
  const mm = minutes % 60 ? `:${String(minutes % 60).padStart(2, "0")}` : "";
  if (lang === "hi") {
    return `${WEEKDAYS.hi[weekdayOf(date)]!.slice(0, 3)} ${day} ${partOfDay(minutes, "hi")} ${h}${mm}`.slice(
      0,
      20,
    );
  }
  return `${WEEKDAYS.en[weekdayOf(date)]!.slice(0, 3)} ${day} ${MONTHS.en[monthIdx]!.slice(0, 3)} ${h}${mm}${minutes < 720 ? "am" : "pm"}`.slice(
    0,
    20,
  );
}
